import type { Category, Account, Settings } from "@/types";
import { nanoid } from "nanoid";

export const defaultCategories: Category[] = [
  // Expense categories
  {
    id: nanoid(),
    name: "Food & Dining",
    type: "expense",
    icon: "🍽️",
    color: "#FF6B6B",
    isCustom: false,
    order: 1,
    subcategories: ["Groceries", "Restaurants", "Fast Food", "Coffee"],
  },
  {
    id: nanoid(),
    name: "Transportation",
    type: "expense",
    icon: "🚗",
    color: "#4ECDC4",
    isCustom: false,
    order: 2,
    subcategories: ["Gas", "Public Transit", "Uber/Taxi", "Parking"],
  },
  {
    id: nanoid(),
    name: "Shopping",
    type: "expense",
    icon: "🛍️",
    color: "#45B7D1",
    isCustom: false,
    order: 3,
    subcategories: ["Clothing", "Electronics", "Home Goods", "Online"],
  },
  {
    id: nanoid(),
    name: "Entertainment",
    type: "expense",
    icon: "🎬",
    color: "#96CEB4",
    isCustom: false,
    order: 4,
    subcategories: ["Movies", "Games", "Subscriptions", "Events"],
  },
  {
    id: nanoid(),
    name: "Bills & Utilities",
    type: "expense",
    icon: "📱",
    color: "#FFEAA7",
    isCustom: false,
    order: 5,
    subcategories: ["Phone", "Internet", "Electricity", "Water"],
  },
  {
    id: nanoid(),
    name: "Healthcare",
    type: "expense",
    icon: "🏥",
    color: "#DDA0DD",
    isCustom: false,
    order: 6,
    subcategories: ["Doctor", "Pharmacy", "Insurance", "Dental"],
  },
  {
    id: nanoid(),
    name: "Home",
    type: "expense",
    icon: "🏠",
    color: "#98D8C8",
    isCustom: false,
    order: 7,
    subcategories: ["Rent", "Mortgage", "Maintenance", "Insurance"],
  },
  {
    id: nanoid(),
    name: "Personal",
    type: "expense",
    icon: "💅",
    color: "#F7DC6F",
    isCustom: false,
    order: 8,
    subcategories: ["Hair", "Gym", "Clothing", "Gifts"],
  },
  {
    id: nanoid(),
    name: "Education",
    type: "expense",
    icon: "📚",
    color: "#BB8FCE",
    isCustom: false,
    order: 9,
    subcategories: ["Courses", "Books", "Supplies", "Tuition"],
  },
  {
    id: nanoid(),
    name: "Travel",
    type: "expense",
    icon: "✈️",
    color: "#85C1E2",
    isCustom: false,
    order: 10,
    subcategories: ["Flights", "Hotels", "Activities", "Food"],
  },
  {
    id: nanoid(),
    name: "Savings",
    type: "expense",
    icon: "💰",
    color: "#82E0AA",
    isCustom: false,
    order: 11,
    subcategories: ["Emergency Fund", "Retirement", "Investment", "Goals"],
  },
  {
    id: nanoid(),
    name: "Other",
    type: "expense",
    icon: "📌",
    color: "#C0C0C0",
    isCustom: false,
    order: 12,
  },

  // Income categories
  {
    id: nanoid(),
    name: "Salary",
    type: "income",
    icon: "💵",
    color: "#27AE60",
    isCustom: false,
    order: 1,
  },
  {
    id: nanoid(),
    name: "Freelance",
    type: "income",
    icon: "💻",
    color: "#3498DB",
    isCustom: false,
    order: 2,
  },
  {
    id: nanoid(),
    name: "Business",
    type: "income",
    icon: "💼",
    color: "#9B59B6",
    isCustom: false,
    order: 3,
  },
  {
    id: nanoid(),
    name: "Investment",
    type: "income",
    icon: "📈",
    color: "#E67E22",
    isCustom: false,
    order: 4,
  },
  {
    id: nanoid(),
    name: "Gift",
    type: "income",
    icon: "🎁",
    color: "#E74C3C",
    isCustom: false,
    order: 5,
  },
  {
    id: nanoid(),
    name: "Refund",
    type: "income",
    icon: "↩️",
    color: "#1ABC9C",
    isCustom: false,
    order: 6,
  },
  {
    id: nanoid(),
    name: "Other Income",
    type: "income",
    icon: "💸",
    color: "#95A5A6",
    isCustom: false,
    order: 7,
  },
];

export const defaultAccounts: Account[] = [
  {
    id: nanoid(),
    name: "Cash",
    type: "cash",
    balance: 0,
    currency: "USD",
    color: "#27AE60",
    isArchived: false,
    order: 1,
  },
  {
    id: nanoid(),
    name: "Checking",
    type: "debit",
    balance: 0,
    currency: "USD",
    color: "#3498DB",
    isArchived: false,
    order: 2,
  },
  {
    id: nanoid(),
    name: "Savings",
    type: "savings",
    balance: 0,
    currency: "USD",
    color: "#9B59B6",
    isArchived: false,
    order: 3,
  },
  {
    id: nanoid(),
    name: "Credit Card",
    type: "credit",
    balance: 0,
    currency: "USD",
    color: "#E74C3C",
    isArchived: false,
    order: 4,
  },
];

export const defaultSettings: Omit<Settings, "id"> = {
  currency: "USD",
  dateFormat: "MM/dd/yyyy",
  startOfWeek: 1,
  theme: "system",
  language: "en",
  notifications: {
    budgetAlerts: true,
    recurringReminders: true,
    dailySummary: false,
  },
  defaultAccount: defaultAccounts[0].id,
  autoBackup: false,
};

export const categoryPatterns: Record<string, string[]> = {
  "Food & Dining": [
    "restaurant",
    "cafe",
    "food",
    "pizza",
    "burger",
    "sushi",
    "grocery",
    "market",
    "walmart",
    "target",
    "whole foods",
    "trader joe",
    "starbucks",
    "mcdonald",
    "subway",
  ],
  Transportation: [
    "uber",
    "lyft",
    "taxi",
    "gas",
    "shell",
    "chevron",
    "exxon",
    "parking",
    "transit",
    "metro",
    "bus",
    "train",
  ],
  Shopping: [
    "amazon",
    "ebay",
    "shop",
    "store",
    "mall",
    "outlet",
    "clothing",
    "fashion",
    "nike",
    "adidas",
    "h&m",
    "zara",
  ],
  Entertainment: [
    "netflix",
    "spotify",
    "hulu",
    "disney",
    "movie",
    "theater",
    "cinema",
    "game",
    "steam",
    "playstation",
    "xbox",
    "nintendo",
  ],
  "Bills & Utilities": [
    "electric",
    "water",
    "gas",
    "internet",
    "phone",
    "verizon",
    "att",
    "tmobile",
    "comcast",
    "spectrum",
  ],
  Healthcare: [
    "pharmacy",
    "cvs",
    "walgreens",
    "doctor",
    "hospital",
    "clinic",
    "dental",
    "medical",
  ],
  Personal: [
    "hair",
    "salon",
    "barber",
    "gym",
    "fitness",
    "spa",
    "massage",
    "nail",
  ],
  Travel: [
    "hotel",
    "airbnb",
    "flight",
    "airline",
    "united",
    "delta",
    "american",
    "southwest",
  ],
};
